# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 2, "", "grpc_service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12grpc_service.proto\x12\x13pytorch_ppo_seed_rl"6\n\nActRequest\x12\x0b\n\x03obs\x18\x01 \x01(\x0c\x12\x0f\n\x07lstm_hx\x18\x02 \x01(\x0c\x12\n\n\x02id\x18\x03 \x01(\t"M\n\x0b\x41\x63tResponse\x12\x0b\n\x03\x61\x63t\x18\x01 \x01(\x0c\x12\x0e\n\x06logits\x18\x02 \x01(\x0c\x12\x10\n\x08log_prob\x18\x03 \x01(\x0c\x12\x0f\n\x07lstm_hx\x18\x04 \x01(\x0c"J\n\x11ReportDataRequest\x12\x0b\n\x03rew\x18\x01 \x01(\x02\x12\x0e\n\x06is_fir\x18\x02 \x01(\x08\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\x12\n\n\x02id\x18\x04 \x01(\t"0\n\x11ReportStatRequest\x12\x0f\n\x07\x65pi_rew\x18\x01 \x01(\x02\x12\n\n\x02id\x18\x02 \x01(\t"\x9e\x01\n\rReportRequest\x12>\n\x0c\x64\x61ta_request\x18\x01 \x01(\x0b\x32&.pytorch_ppo_seed_rl.ReportDataRequestH\x00\x12>\n\x0cstat_request\x18\x02 \x01(\x0b\x32&.pytorch_ppo_seed_rl.ReportStatRequestH\x00\x42\r\n\x0breport_type"\x07\n\x05\x45mpty2\xa3\x01\n\rRunnerService\x12H\n\x03\x41\x63t\x12\x1f.pytorch_ppo_seed_rl.ActRequest\x1a .pytorch_ppo_seed_rl.ActResponse\x12H\n\x06Report\x12".pytorch_ppo_seed_rl.ReportRequest\x1a\x1a.pytorch_ppo_seed_rl.Emptyb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "grpc_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ACTREQUEST"]._serialized_start = 43
    _globals["_ACTREQUEST"]._serialized_end = 97
    _globals["_ACTRESPONSE"]._serialized_start = 99
    _globals["_ACTRESPONSE"]._serialized_end = 176
    _globals["_REPORTDATAREQUEST"]._serialized_start = 178
    _globals["_REPORTDATAREQUEST"]._serialized_end = 252
    _globals["_REPORTSTATREQUEST"]._serialized_start = 254
    _globals["_REPORTSTATREQUEST"]._serialized_end = 302
    _globals["_REPORTREQUEST"]._serialized_start = 305
    _globals["_REPORTREQUEST"]._serialized_end = 463
    _globals["_EMPTY"]._serialized_start = 465
    _globals["_EMPTY"]._serialized_end = 472
    _globals["_RUNNERSERVICE"]._serialized_start = 475
    _globals["_RUNNERSERVICE"]._serialized_end = 638
# @@protoc_insertion_point(module_scope)
